tag_count:
  default: "25"

categories_page_column_count:
  default: "2"
  description: "The number of parent columns on the page"

tag_column_count:
  default: "3"
  description: "The number of columns within the tags section"

hide_categories_column:
  default: false
  description: "Enabling this will hide the categories on the categories page"

categories_column:
  default: "1"
  description: |
    which column categories appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column">grid-column</a>

categories_row:
  default: "2"
  description: |
    which row categories appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row">grid-row</a>

tags_column:
  default: "1"
  description: |
    which column tags appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column">grid-column</a>

tags_row:
  default: "1"
  description: |
    which row tags appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row">grid-row</a>

topics_column:
  default: "2"
  description: |
    which column top or latest topics appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column">grid-column</a>

topics_row:
  default: "1 / span 2"
  description: |
    which row top or latest topics appear in, accepts values supported by <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column">grid-column</a>
