tag_count:
  default: "25"

categories_page_column_count:
  default: "2"

tag_column_count:
  default: "3"

hide_categories_column:
  default: false

categories_column:
  default: "1"

categories_row:
  default: "2"

tags_column:
  default: "1"

tags_row:
  default: "1"

topics_column:
  default: "2"

topics_row:
  default: "1 / span 2"
